                                                    ### Backend Deployment ###
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  # namespace: thurvpn
  labels:
    app: backend-deployment
spec:
  replicas: 6
  selector:
    matchLabels:
      app: backend-deployment
  template:
    metadata:
      labels:
        app: backend-deployment
    spec:    
      containers:
      - name: thurvpn-backend
        image: $IMAGE_REPO:$imageVersion
        imagePullPolicy: Always
        ports:
        - containerPort: 2023
        resources:
          requests:
            memory: 125Mi
        livenessProbe:
          httpGet:
            path: /jobs/all
            port: 80
            host: 164.90.241.26
            scheme: HTTP
          initialDelaySeconds: 180
          periodSeconds: 30
      restartPolicy: Always

