                                                    ### Backend Deployment ###
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: thurnamespace
  labels:
    app: backend-deployment
spec:
  replicas: 6
  selector:
    matchLabels:
      app: backend-deployment
  template:
    metadata:
      labels:
        app: backend-deployment
    spec:    
      containers:
      - name: thurvpn-backend
        image: 844268948863.dkr.ecr.us-west-1.amazonaws.com/thurvpnapi:0.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: 125Mi
        livenessProbe:
          httpGet:
            path: /jobs/all
            port: 80
            host: 164.90.241.26
            scheme: HTTP
          initialDelaySeconds: 180
          periodSeconds: 30
      restartPolicy: Always
---
                                                    ### Backend Service ###
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: backend-deployment
  namespace: thurnamespace
spec:
   type: LoadBalancer 
   ports: 
     - name: backend
       port: 80
       targetPort: 3000
     - name: backend-ssl
       port: 443
       targetPort: 3000
   selector:
     app: backend-deployment

---
                                                    ### Backend HPA ###
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-hpa
  namespace: thurnamespace
spec:
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 10
      policies:
      - type: Percent
        value: 30
        periodSeconds: 60
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend-deployment
  minReplicas: 6
  maxReplicas: 20
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 85
