apiVersion: apps/v1
kind: Deployment
metadata:
  name: thurvpnapi
  labels:
    app: thurvpnapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: thurvpnapi
  template:
    metadata:
      name: thurvpnapi
      labels:
        app: thurvpnapi
    spec:
      imagePullSecrets:
      - name: my-ecr-registry
      containers:
      - name: thurvpnapi
        image: 844268948863.dkr.ecr.us-west-1.amazonaws.com/thurvpnapi:0.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 3000

