apiVersion: apps/v1
kind: Deployment
metadata:
  name: thurvpnapi
  namespace: thurvpn
spec:
  replicas: 2
  selector:
    matchLabels:
      app: thurvpnapi
  template:
  - metadata:
      labels:
        app: thurvpnapi
    spec:
      containers:
        - name: thurvpnapi-container
          image: 844268948863.dkr.ecr.us-west-1.amazonaws.com/thurvpnapi:$imageVersion
          ports:
            - containerPort: 3000
            
---
apiVersion: v1
kind: Service
metadata:
  name: thurvpn-api-service
  namespace: thurvpn
spec:
  selector:
    app: thurvpnapi
  ports:
    - name: http
      port: 80
      targetPort: 3000
    -name: backend-ssl
      port: 443
      targetPort: 3000
  type: LoadBalancer
    - name: thurvpnapi-loadbalancer

---   
                                                            ### THURVPN_API HPA ###

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: thurvpnapi-hpa
  namespace: thurvpn
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: thurvpnapi
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
