apiVersion: apps/v1
kind: Deployment
metadata:
  name: thurvpnapi
  labels:
    app: thurvpnapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: thurvpnapi
  template:
    metadata:
      labels:
        app: thurvpnapi
    spec:
      imagePullSecrets:
        - name: my-ecr-registry
      containers:
        - name: thurvpnapi
          image: $IMAGE_REPO:$imageVersion
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: 115Mi
              cpu: 100m
              