apiVersion: apps/v1
kind: Deployment
metadata:
  name: thurvpnapi
  labels:
    app: thurvpnapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thurvpnapi
  template:
    metadata:
      name: thurvpnapi
      labels:
        app: thurvpnapi
    spec:
      imagePullSecrets:
      - name: my-ecr-registry
      containers:
      - name: thurvpnapi
        image: $IMAGE_REPO:$imageVersion
        imagePullPolicy: Always
        ports:
        - containerPort: 3000

