apiVersion: v1
kind: Service
metadata:
  name: thurvpnapisvc
  labels:
    app: thurvpnapi
spec:
   type: LoadBalancer 
   ports: 
     - name: thurvpnapi
       port: 80
       targetPort: 3000
     - name: thurvpnapi-ssl
       port: 443
       targetPort: 3000

   selector:
     app: thurvpnapi