apiVersion: apps/v1
kind: Deployment
metadata:
  name: thurvpnapi
  labels:
    app: thurvpnapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: thurvpnapi
  template:
    metadata:
      labels:
        app: thurvpnapi
    spec:
      nodeSelector:
        doks.digitalocean.com/node-pool: "thurvpnapi-pool"
      restartPolicy: Always
      containers:
      - name: thurvpnapi
        image: $regName/$imageName:$imageVersion
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
