apiVersion: apps/v1
kind: Deployment
metadata:
  name: thurvpnapi
  labels:
    app: thurvpnapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: thurvpnapi
  template:
    metadata:
      labels:
        app: thurvpnapi
    spec:
      imagePullSecrets:
        - name: aws-ecr-key
      containers:
      - name: thurvpnapi
        image: 844268948863.dkr.ecr.us-west-1.amazonaws.com/thurvpnapi:$imageVersion
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
